# Site settings
title: Vagrant Host
email: info@codingcoop.org
description: "A service which keeps DNS in sync with your Vagrantfile."
baseurl: "/"
url: "http://vagrant.host"

author:
  name: "The Coding Cooperative"

# Build settings
markdown: redcarpet
permalink: pretty

